### ISSUE TITLE
Create new world buttons issue

### ISSUE THREAD

**Issue by TheDarkPreacher** [Boomflex/JustNotEnoughMods#1]
Start pack, hit create new world, greeted by the following. goes away when "More World Options" is clicked.
Happens in version 0.2.0 and 0.3.0 of the pack.

![image](https://user-images.githubusercontent.com/15058826/68507193-ef9dbf80-0230-11ea-936f-befff0618761.png)

**Comment by Boomflex** [comment]
This was caused by the mod "No Recipe Book".

Reporting to Mod Dev.

Thanks for reminding me :)
