### ISSUE TITLE
Lighting Issues

### ISSUE THREAD

**Issue by ghost** [Boomflex/JustNotEnoughMods#11]
Appears that on the server chunks containing Botania equipment are becoming dark and are not correctly updating lighting. The are dark on relog/reboot and we haven't been able to reactivate lighting updates. Looks to be this issue https://github.com/Vazkii/Botania/issues/3140

**Comment by Boomflex** [comment]
Yeah, I had noticed it myself and saw it on their Github.

From a Pack Dev POV there is little to nothing at all I can do as is a Forge issue I am afraid.
