### ISSUE TITLE
0.3.9 Rendering Screen Crash

### ISSUE THREAD

**Issue by furkanmavi** [Boomflex/JustNotEnoughMods#5]
Hi,

After the 0.3.9 update, whenever I open my inventory, game crashes in a few seconds. Actually it kills whole Minecraft, not just the world. I tried few times  to reproduce the crash and it happened every time. And a side note: Modpack comes with Forge 28.1.99, instead of 28.1.108 as mentioned at the changelog.
Crash report is down below.

https://pastebin.com/1FBjwtfs

**Comment by Boomflex** [comment]
Oh this is very weird...

Is it happening by any chance when you hover over any tools made by Silent's Gear?

**Comment by Boomflex** [comment]
Removed the Forge update part of the changelog.

Forge removed 108 so I didn't update it in the end.

**Comment by furkanmavi** [comment]
Yes, tried it now. Just like you say, exact moment hover over a Silent's Gear pickaxe, it shuts Minecraft entirely.

**Comment by Boomflex** [comment]
That is what the crashlog looked like.

I have forwarded the crash dump to Silent to take a look... for now I will
say dump all your items apart from the Silents pickaxe in to a chest, then
when it is JUST the pickaxe, enable cheats and do /clear this will delete
the pickaxe without having to hover over it.

**Comment by furkanmavi** [comment]
Okay, thanks for help and advice. Very appreciated.

**Comment by Boomflex** [comment]
Silent has closed the issue but I will keep it open until the update comes out and I can test it myself

Thanks again for letting me know :)

https://github.com/SilentChaos512/Silent-Gear/commit/b7f522188b8eba6d5d3e873340ce3287677ff3c4

**Comment by Boomflex** [comment]
Ok, they pushed their update so I pushed a real quick update.

https://www.curseforge.com/minecraft/modpacks/just-not-enough-mods/files/2849697

Let me know if this sorts it for you :)

**Comment by furkanmavi** [comment]
And boom, it fixed my issue! I have a non-crushing tooltip now :)

![tooltip](https://user-images.githubusercontent.com/16275104/71476964-a9101e80-27f8-11ea-8ab6-cb115127eab2.png)

**Comment by Boomflex** [comment]
That is perfect! Thanks for letting me know and thanks for playing the pack :)

If there are any mods or changes you'd like to be made, I am always up for input!
