### ISSUE TITLE
Cant make block of botania manasteel

### ISSUE THREAD

**Issue by MrThreat** [Boomflex/JustNotEnoughMods#7]
The recipe for a block of manasteel doesn't work, it only lets you make JAOPCA versions and there is no way to make the botania one, so we cant make a botania portal.

**Comment by Boomflex** [comment]
Fixed in 0.4.4

![image](https://user-images.githubusercontent.com/22868795/72610650-d8114000-391f-11ea-8785-4e369dbe556d.png)
